import type { WorkspaceBootstrapSnapshot } from "../../src/lib/app-types";

export const sampleWorkspaceSnapshot: WorkspaceBootstrapSnapshot = {
  app_name: "Workspace",
  generated_at: "2026-04-05T09:00:00Z",
  default_view: "recent_verification",
  navigation: [
    {
      id: "recent_verification",
      label: "Recent verification",
      badge: 2,
    },
    {
      id: "all_inbox",
      label: "All inbox",
      badge: 3,
    },
    {
      id: "site_list",
      label: "Sites",
      badge: 3,
    },
    {
      id: "accounts",
      label: "Accounts",
      badge: 1,
    },
  ],
  mailboxes: [
    {
      id: "acct_primary-example-com/inbox",
      account_id: "acct_primary-example-com",
      account_name: "Primary Gmail",
      label: "Inbox",
      kind: "inbox",
      total_count: 2,
      unread_count: 2,
      verification_count: 2,
    },
    {
      id: "acct_primary-example-com/spam-junk",
      account_id: "acct_primary-example-com",
      account_name: "Primary Gmail",
      label: "Spam/Junk",
      kind: "spam_junk",
      total_count: 1,
      unread_count: 0,
      verification_count: 1,
    },
  ],
  message_groups: [
    {
      id: "pending",
      label: "待处理",
      items: [
        {
          id: "msg_github_security",
          account_id: "acct_primary-example-com",
          subject: "GitHub 安全验证码",
          sender: "noreply@github.com",
          account_name: "Primary Gmail",
          mailbox_id: "acct_primary-example-com/inbox",
          mailbox_label: "Inbox",
          received_at: "2026-04-05T08:58:00Z",
          category: "security",
          status: "pending",
          read_state: "unread",
          has_code: true,
          has_link: true,
          preview: "你的 GitHub 登录验证码是 362149。",
          prefetched_body: true,
          synced_at: "2026-04-05T09:00:00Z",
        },
        {
          id: "msg_linear_verify",
          account_id: "acct_primary-example-com",
          subject: "Linear 验证链接",
          sender: "hello@linear.app",
          account_name: "Primary Gmail",
          mailbox_id: "acct_primary-example-com/inbox",
          mailbox_label: "Inbox",
          received_at: "2026-04-05T08:41:00Z",
          category: "registration",
          status: "pending",
          read_state: "unread",
          has_code: false,
          has_link: true,
          preview: "点击邮件里的安全链接完成登录。",
          prefetched_body: true,
          synced_at: "2026-04-05T09:00:00Z",
        },
      ],
    },
    {
      id: "processed",
      label: "已处理",
      items: [
        {
          id: "msg_notion_welcome",
          account_id: "acct_primary-example-com",
          subject: "Notion 欢迎邮件",
          sender: "team@makenotion.com",
          account_name: "Primary Gmail",
          mailbox_id: "acct_primary-example-com/spam-junk",
          mailbox_label: "Spam/Junk",
          received_at: "2026-04-02T07:12:00Z",
          category: "marketing",
          status: "processed",
          read_state: "read",
          has_code: false,
          has_link: true,
          preview: "欢迎继续完成 Notion 设置。",
          prefetched_body: true,
          synced_at: "2026-04-05T09:00:00Z",
        },
      ],
    },
  ],
  selected_message: {
    id: "msg_github_security",
    account_id: "acct_primary-example-com",
    subject: "GitHub 安全验证码",
    sender: "noreply@github.com",
    account_name: "Primary Gmail",
    mailbox_id: "acct_primary-example-com/inbox",
    mailbox_label: "Inbox",
    received_at: "2026-04-05T08:58:00Z",
    category: "security",
    status: "pending",
    read_state: "unread",
    site_hint: "github.com",
    summary: "你的 GitHub 登录验证码是 362149。",
    extracted_code: "362149",
    verification_link: "https://github.com/login/device",
    original_message_url:
      "https://mail.google.com/mail/u/0/#inbox/msg_github_security",
    body_text: "你的 GitHub 登录验证码是 362149。",
    prefetched_body: true,
    synced_at: "2026-04-05T09:00:00Z",
  },
  message_details: [
    {
      id: "msg_github_security",
      account_id: "acct_primary-example-com",
      subject: "GitHub 安全验证码",
      sender: "noreply@github.com",
      account_name: "Primary Gmail",
      mailbox_id: "acct_primary-example-com/inbox",
      mailbox_label: "Inbox",
      received_at: "2026-04-05T08:58:00Z",
      category: "security",
      status: "pending",
      read_state: "unread",
      site_hint: "github.com",
      summary: "你的 GitHub 登录验证码是 362149。",
      extracted_code: "362149",
      verification_link: "https://github.com/login/device",
      original_message_url:
        "https://mail.google.com/mail/u/0/#inbox/msg_github_security",
      body_text: "你的 GitHub 登录验证码是 362149。",
      prefetched_body: true,
      synced_at: "2026-04-05T09:00:00Z",
    },
    {
      id: "msg_linear_verify",
      account_id: "acct_primary-example-com",
      subject: "Linear 验证链接",
      sender: "hello@linear.app",
      account_name: "Primary Gmail",
      mailbox_id: "acct_primary-example-com/inbox",
      mailbox_label: "Inbox",
      received_at: "2026-04-05T08:41:00Z",
      category: "registration",
      status: "pending",
      read_state: "unread",
      site_hint: "linear.app",
      summary: "点击邮件里的安全链接完成登录。",
      extracted_code: null,
      verification_link: "https://linear.app/login",
      original_message_url: "https://outlook.office.com/mail/id/msg_linear_verify",
      body_text: "点击邮件里的安全链接完成登录。",
      prefetched_body: true,
      synced_at: "2026-04-05T09:00:00Z",
    },
    {
      id: "msg_notion_welcome",
      account_id: "acct_primary-example-com",
      subject: "Notion 欢迎邮件",
      sender: "team@makenotion.com",
      account_name: "Primary Gmail",
      mailbox_id: "acct_primary-example-com/spam-junk",
      mailbox_label: "Spam/Junk",
      received_at: "2026-04-02T07:12:00Z",
      category: "marketing",
      status: "processed",
      read_state: "read",
      site_hint: "notion.so",
      summary: "欢迎继续完成 Notion 设置。",
      extracted_code: null,
      verification_link: "https://www.notion.so",
      original_message_url:
        "https://mail.google.com/mail/u/0/#spam/msg_notion_welcome",
      body_text: "欢迎继续完成 Notion 设置。",
      prefetched_body: true,
      synced_at: "2026-04-05T09:00:00Z",
    },
  ],
  extracts: [
    {
      id: "extract_github_code",
      sender: "GitHub",
      kind: "code",
      value: "362149",
      label: "",
      progress_percent: 84,
      expires_label: "8m",
    },
    {
      id: "extract_linear_link",
      sender: "Linear",
      kind: "link",
      value: "https://linear.app/login",
      label: "Open login link",
      progress_percent: 42,
      expires_label: "4m",
    },
  ],
  site_summaries: [
    {
      id: "site_github",
      label: "GitHub",
      hostname: "github.com",
      pending_count: 1,
      latest_sender: "noreply@github.com",
    },
    {
      id: "site_linear",
      label: "Linear",
      hostname: "linear.app",
      pending_count: 1,
      latest_sender: "hello@linear.app",
    },
    {
      id: "site_notion",
      label: "Notion",
      hostname: "notion.so",
      pending_count: 0,
      latest_sender: "team@makenotion.com",
    },
  ],
  sync_status: {
    state: "ready",
    summary: "已同步 1 个账号，共 3 封邮件",
    phase: "first",
    poll_interval_minutes: 3,
    retention_days: 30,
    next_poll_at: "2026-04-05T09:03:00Z",
    folders: ["Inbox", "Spam/Junk"],
  },
};

export function createSampleWorkspaceSnapshot(): WorkspaceBootstrapSnapshot {
  return structuredClone(sampleWorkspaceSnapshot);
}
